[versions]
idea = "243.21155.17"
kotlin = "2.0.10"

[plugins]
intellijPlatform = { id = "org.jetbrains.intellij.platform", version = "2.0.1"}
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
